"""updates password len

Revision ID: afa29f5b5013
Revises: e7b50c96471d
Create Date: 2024-10-24 18:43:11.869388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'afa29f5b5013'
down_revision: Union[str, None] = 'e7b50c96471d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'books', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_constraint(None, 'books', type_='foreignkey')
    # ### end Alembic commands ###
